
version: "3.8"

services:
  app:
    build: .
    container_name: sparta-app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: "mongodb://mongo:27017"
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: sparta-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  seed:
    build: .
    container_name: sparta-seed
    command: npm install 
    environment:
      DB_HOST: "mongodb://mongo:27017"
    depends_on:
      - mongo
    restart: "no"

volumes:
  mongo-data:

